Exception in thread Thread-10:
Traceback (most recent call last):
  File "/home/smajumd3/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "run.py", line 44, in run
    **self._kwargs)
  File "run.py", line 70, in mine
    get_matrix = git_understand.MetricsGetter(git_url,repo_name,repo_lang,code_path)
  File "/home/smajumd3/Data_Miner/github/API_V3/git_understand/git_understand_v1.py", line 83, in __init__
    self.buggy_clean_pairs = self.read_commits()
  File "/home/smajumd3/Data_Miner/github/API_V3/git_understand/git_understand_v1.py", line 117, in read_commits
    df = pd.read_csv(self.file_path)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'/home/smajumd3/Data_Miner/github/data/commit_guru/glide.csv' does not exist: b'/home/smajumd3/Data_Miner/github/data/commit_guru/glide.csv'

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/smajumd3/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "run.py", line 44, in run
    **self._kwargs)
  File "run.py", line 70, in mine
    get_matrix = git_understand.MetricsGetter(git_url,repo_name,repo_lang,code_path)
  File "/home/smajumd3/Data_Miner/github/API_V3/git_understand/git_understand_v1.py", line 83, in __init__
    self.buggy_clean_pairs = self.read_commits()
  File "/home/smajumd3/Data_Miner/github/API_V3/git_understand/git_understand_v1.py", line 117, in read_commits
    df = pd.read_csv(self.file_path)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'/home/smajumd3/Data_Miner/github/data/commit_guru/metrics.csv' does not exist: b'/home/smajumd3/Data_Miner/github/data/commit_guru/metrics.csv'

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/smajumd3/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "run.py", line 44, in run
    **self._kwargs)
  File "run.py", line 70, in mine
    get_matrix = git_understand.MetricsGetter(git_url,repo_name,repo_lang,code_path)
  File "/home/smajumd3/Data_Miner/github/API_V3/git_understand/git_understand_v1.py", line 83, in __init__
    self.buggy_clean_pairs = self.read_commits()
  File "/home/smajumd3/Data_Miner/github/API_V3/git_understand/git_understand_v1.py", line 117, in read_commits
    df = pd.read_csv(self.file_path)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'/home/smajumd3/Data_Miner/github/data/commit_guru/jsoup.csv' does not exist: b'/home/smajumd3/Data_Miner/github/data/commit_guru/jsoup.csv'

Exception in thread Thread-15:
Traceback (most recent call last):
  File "/home/smajumd3/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "run.py", line 44, in run
    **self._kwargs)
  File "run.py", line 70, in mine
    get_matrix = git_understand.MetricsGetter(git_url,repo_name,repo_lang,code_path)
  File "/home/smajumd3/Data_Miner/github/API_V3/git_understand/git_understand_v1.py", line 83, in __init__
    self.buggy_clean_pairs = self.read_commits()
  File "/home/smajumd3/Data_Miner/github/API_V3/git_understand/git_understand_v1.py", line 117, in read_commits
    df = pd.read_csv(self.file_path)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'/home/smajumd3/Data_Miner/github/data/commit_guru/cassandra.csv' does not exist: b'/home/smajumd3/Data_Miner/github/data/commit_guru/cassandra.csv'

Exception in thread Thread-13:
Traceback (most recent call last):
  File "/home/smajumd3/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "run.py", line 44, in run
    **self._kwargs)
  File "run.py", line 70, in mine
    get_matrix = git_understand.MetricsGetter(git_url,repo_name,repo_lang,code_path)
  File "/home/smajumd3/Data_Miner/github/API_V3/git_understand/git_understand_v1.py", line 83, in __init__
    self.buggy_clean_pairs = self.read_commits()
  File "/home/smajumd3/Data_Miner/github/API_V3/git_understand/git_understand_v1.py", line 117, in read_commits
    df = pd.read_csv(self.file_path)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/smajumd3/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'/home/smajumd3/Data_Miner/github/data/commit_guru/storm.csv' does not exist: b'/home/smajumd3/Data_Miner/github/data/commit_guru/storm.csv'
16
                      repo_name repo_owner  ... commits defective
0              coursera-android    aporter  ...     135         9
1  Android-ObservableScrollView  ksoichiro  ...     383        80

[2 rows x 9 columns]
  repo_name repo_owner  ... commits defective
0    dagger     square  ...     701       144
1   picasso     square  ...    1364       183

[2 rows x 9 columns]
  repo_name  repo_owner  ... commits defective
0  Telegram       DrKLO  ...     342       193
1  greenDAO  greenrobot  ...     857       195

[2 rows x 9 columns]
     repo_name     repo_owner  ... commits defective
0  springside4     springside  ...    1074       213
1    disruptor  LMAX-Exchange  ...     958       214

[2 rows x 9 columns]
           repo_name   repo_owner  ... commits defective
0  ActionBarSherlock  JakeWharton  ...    1480       219
1          roboguice    roboguice  ...    1054       222

[2 rows x 9 columns]
              repo_name repo_owner  ... commits defective
0               Hystrix    Netflix  ...    2109       241
1  facebook-android-sdk   facebook  ...    1355       250

[2 rows x 9 columns]
      repo_name repo_owner  ... commits defective
0         jsoup        jhy  ...    1261       355
1  AndroidAsync      koush  ...    1081       361

[2 rows x 9 columns]
  repo_name  repo_owner  ... commits defective
0   metrics  dropwizard  ...    2580       429
1     junit  junit-team  ...    2427       544

[2 rows x 9 columns]
            repo_name repo_owner  ... commits defective
0  androidannotations    excilys  ...    2908       583
1               zxing      zxing  ...    3521       847

[2 rows x 9 columns]
  repo_name repo_owner  ... commits defective
0     glide   bumptech  ...    2445       873
1    okhttp     square  ...    4391       967

[2 rows x 9 columns]
  repo_name repo_owner  ... commits defective
0     guava     google  ...    5172      1348
1    vert.x    eclipse  ...    4225      1404

[2 rows x 9 columns]
  repo_name     repo_owner  ... commits defective
0     titan  thinkaurelius  ...    4434      1563
1     druid        alibaba  ...    6057      1852

[2 rows x 9 columns]
    repo_name repo_owner  ... commits defective
0       storm     apache  ...   10192      1873
1  realm-java      Realm  ...    8261      1912

[2 rows x 9 columns]
  repo_name repo_owner  ... commits defective
0     netty      netty  ...    9674      3297
1    libgdx     libgdx  ...   13924      3678

[2 rows x 9 columns]
   repo_name repo_owner  ... commits defective
0  cassandra     apache  ...   24868      4155

[1 rows x 9 columns]
  repo_name repo_owner  ... commits defective
0    presto   facebook  ...   16688      4310

[1 rows x 9 columns]
I am here
I am here
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
I am here
I am here
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
I am here
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
I am here
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
I am here
I am here
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
I am here
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
I am here
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
I am here
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
I am here
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
I am here
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
I am here
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
I am here
I am here
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
/home/smajumd3/Data_Miner/github/API_V3
root: /home/smajumd3/Data_Miner/github/API_V3
['04892c03bad8cc45a3c509880c33e7f1d41f5a47', '70eee483d7b2cde633f2ff93fbe9b73c5612ce2b']
cwd /home/smajumd3/Data_Miner/github/API_V3
udb at init /home/smajumd3/Data_Miner/github/API_V3/temp/udb/dagger
141
0 dagger ('04892c03bad8cc45a3c509880c33e7f1d41f5a47', '70eee483d7b2cde633f2ff93fbe9b73c5612ce2b')
['80de9cf1288f6ea27c5d98cb8f9f6b26b69bcb76', 'f5ec53d30d3607b0af069980408e2748f10a563d']
cwd /home/smajumd3/Data_Miner/github/API_V3
udb at init /home/smajumd3/Data_Miner/github/API_V3/temp/udb/coursera-android
9
0 coursera-android ('80de9cf1288f6ea27c5d98cb8f9f6b26b69bcb76', 'f5ec53d30d3607b0af069980408e2748f10a563d')
['2e41a206c204e32de1deb2c86c60699d3202c13c', '71ee99d51501b86a350bff5928fcf48cd6ac3182']
cwd /home/smajumd3/Data_Miner/github/API_V3
udb at init /home/smajumd3/Data_Miner/github/API_V3/temp/udb/springside4
213
0 springside4 ('2e41a206c204e32de1deb2c86c60699d3202c13c', '71ee99d51501b86a350bff5928fcf48cd6ac3182')
at und file dagger /home/smajumd3/Data_Miner/github/API_V3/temp/udb/dagger /home/smajumd3/Data_Miner/github/API_V3/temp/udb/dagger/dagger04892c03bad8cc45a3c509880c33e7f1d41f5a47_buggy.udb
['27b74b537eb74ecbe02c068a6e03940b2fa87334', 'c824df619a0367105ca485dc8828f2a498e2d667']
cwd /home/smajumd3/Data_Miner/github/API_V3
udb at init /home/smajumd3/Data_Miner/github/API_V3/temp/udb/Telegram
194
0 Telegram ('27b74b537eb74ecbe02c068a6e03940b2fa87334', 'c824df619a0367105ca485dc8828f2a498e2d667')
at und file springside4 /home/smajumd3/Data_Miner/github/API_V3/temp/udb/springside4 /home/smajumd3/Data_Miner/github/API_V3/temp/udb/springside4/springside42e41a206c204e32de1deb2c86c60699d3202c13c_buggy.udb
['c5dd88986c0177f506730f7ef9064c1dafbc4f04', '3a5e7f3e1dc138a421fe98fc828d92c05467d45a']
cwd /home/smajumd3/Data_Miner/github/API_V3
udb at init /home/smajumd3/Data_Miner/github/API_V3/temp/udb/ActionBarSherlock
219
0 ActionBarSherlock ('c5dd88986c0177f506730f7ef9064c1dafbc4f04', '3a5e7f3e1dc138a421fe98fc828d92c05467d45a')
['ee89c24b958d3f045ca29d9dbadc4d6b56e40bc5', '4412e99999fc693ae67743622e84f06f3f7acdc4']
cwd /home/smajumd3/Data_Miner/github/API_V3
udb at init /home/smajumd3/Data_Miner/github/API_V3/temp/udb/Hystrix
241
0 Hystrix ('ee89c24b958d3f045ca29d9dbadc4d6b56e40bc5', '4412e99999fc693ae67743622e84f06f3f7acdc4')
['dc5915eb1072c61ff2c3c704af4ae36b25f97b6c', 'db3929bd79ef57f8da40515b663f40200a941fa8']
cwd /home/smajumd3/Data_Miner/github/API_V3
udb at init /home/smajumd3/Data_Miner/github/API_V3/temp/udb/guava
1349
0 guava ('dc5915eb1072c61ff2c3c704af4ae36b25f97b6c', 'db3929bd79ef57f8da40515b663f40200a941fa8')
at und file ActionBarSherlock /home/smajumd3/Data_Miner/github/API_V3/temp/udb/ActionBarSherlock /home/smajumd3/Data_Miner/github/API_V3/temp/udb/ActionBarSherlock/ActionBarSherlockc5dd88986c0177f506730f7ef9064c1dafbc4f04_buggy.udb
at und file Hystrix /home/smajumd3/Data_Miner/github/API_V3/temp/udb/Hystrix /home/smajumd3/Data_Miner/github/API_V3/temp/udb/Hystrix/Hystrixee89c24b958d3f045ca29d9dbadc4d6b56e40bc5_buggy.udb
at und file coursera-android /home/smajumd3/Data_Miner/github/API_V3/temp/udb/coursera-android /home/smajumd3/Data_Miner/github/API_V3/temp/udb/coursera-android/coursera-android80de9cf1288f6ea27c5d98cb8f9f6b26b69bcb76_buggy.udb
at und file guava /home/smajumd3/Data_Miner/github/API_V3/temp/udb/guava /home/smajumd3/Data_Miner/github/API_V3/temp/udb/guava/guavadc5915eb1072c61ff2c3c704af4ae36b25f97b6c_buggy.udb
at und file Telegram /home/smajumd3/Data_Miner/github/API_V3/temp/udb/Telegram /home/smajumd3/Data_Miner/github/API_V3/temp/udb/Telegram/Telegram27b74b537eb74ecbe02c068a6e03940b2fa87334_buggy.udb
at und file ActionBarSherlock /home/smajumd3/Data_Miner/github/API_V3/temp/udb/ActionBarSherlock /home/smajumd3/Data_Miner/github/API_V3/temp/udb/ActionBarSherlock/ActionBarSherlockc5dd88986c0177f506730f7ef9064c1dafbc4f04_clean.udb
at und file springside4 /home/smajumd3/Data_Miner/github/API_V3/temp/udb/springside4 /home/smajumd3/Data_Miner/github/API_V3/temp/udb/springside4/springside42e41a206c204e32de1deb2c86c60699d3202c13c_clean.udbslurmstepd: error: *** JOB 180505 ON c8 CANCELLED AT 2020-01-15T14:57:08 ***
